---
- name: update users
  hosts: localhost
  gather_facts: false
  become: yes

  vars:
    s_user: 'pentest'
  tasks:

  - name: GETENT {{s_user}} info
    getent:
      database: passwd
      key: "{{s_user}}"
    ignore_errors: yes

  - name: Fail if user does not exist
    fail:
      msg: "User {{ s_user }} does not exist, moving on"
    when: ansible_facts.getent_passwd["{{s_user}}"] is not defined

  - debug:
      var: ansible_facts.getent_passwd