---
- name: time test
  hosts: localhost
  gather_facts: false
  tasks:

  - debug:
      msg="{{ lookup('pipe','date +%s -d now+6months')| float }}"
      # msg: "{{ ('date  '|to_datetime).strftime('%s') }}"
  
  
  # - name: Change expiry date for user to today + 6 months
  #   ansible.builtin.user:
  #     name: pentest
  #     expires: -1